// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1020
package main

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func about() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<!doctype html><html>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = style().Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "<body><div class=\"center\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = homebutton().Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = links().Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "<h3>About this site:</h3><p>This site is meant to allow you to view the history of memes as they develop over time. It is part archive, part reference, and part visualization.  To learn more about what a meme is, <a href=\"https://en.wikipedia.org/wiki/Meme\">see this introduction on wikipedia</a>. </p><p>This site tracks memetic history by storing individual memes in trees. Each tree starts with a LUCA (last universal common ancestor): a meme with no linked ancestors. Of course, very few memes start from nowhere: a LUCA is somewhat subjective, and can be updated over time as new ancestors are discovered. This LUCA will then have offspring, sometimes multiple offspring. These offspring are individually referred to as variants. Variants will also have offspring, picking up new traits from other parents and combining, mutating, and passing along these traits. Thus, the tree of memes will grow.</p><p>Memes can be submitted by anyone, in order to allow for the representation of much information as possible. However, all data that appears on the publicly available website has been verified as the admins of this website. Original posters will generally not preserved, since the whole point of this site is to show how different ideas mix together. Therefore, attributing individual credit would be very difficult and prone to many arguments. Original dates will try to be preserved when possible for archival purposes. </p><p>This site is run by <a href=\"https://nlessard.online\">Noah Lessard</a> and <a href=\"https://salm.dev\">Nico Salm</a>. It is run for free, please donate by recommending the site to other people, submitting a meme or becoming a moderator.</p></div></body></html>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
