// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1020
package main

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func style() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<head><title>Memetic Tree</title><style>\n  h1 {color:red;}\n\n  a {\n    color: blue;\n  }\n\n  a:visited {\n    color: blue;\n  }\n\n  table {\n    margin: 0 auto;\n    border-collapse: collapse;\n  }\n\n  th, td {\n    border: 1px solid #000000;\n    padding: 8px;\n  }\n\n  .center {\n    text-align: center;\n    max-width: 75%;\n    margin: auto;\n  }\n\n  .center-image-text {\n    display: flex;\n    align-items: center;\n    gap: 30px;\n    justify-content: center;\n  }\n\n  @media (max-width: 800px) {\n    .center-image-text {\n      display: block;\n      align-items: center;\n      justify-content: center;\n    }\n\n  }\n\n  .main-img {\n    height: 400px;\n  }\n\n  .tree-img {\n    max-width: 30vw;\n    height: auto;\n    width: auto;\n  }\n\n  .h2-row {\n    display: flex;\n    gap: 20px;\n    justify-content: center;\n  }\n\n  .border {\n    border: solid black 2px;\n    max-width: 600px;\n    padding-left: 5%;\n    padding-right: 5%;\n    margin: auto;\n  }\n\n  .invis {\n    color: red;\n    text-decoration: underline;\n  }\n\n  .invis:visited {\n    color: red;  /* Keep the same styling as unvisited */\n    text-decoration: underline;\n  }\n\n</style></head>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
